MemberFormatter.cs: Fix compilation against Mono mscorlib.dll
It contains an internal Mono.Math namespace which confuses the compiler and causes:

```
MemberFormatter.cs(74,28): error CS0234: The type or namespace name 'Max' does not exist in the namespace 'Mono.Math' (are you missing an assembly reference?)
```