Fix the build.
Mono.Documentation/webdoc.cs(199,87): warning CS0618: `Monodoc.Node.Nodes' is obsolete: `Use ChildNodes'
Mono.Documentation/webdoc.cs(199,87): error CS0266: Cannot implicitly convert type `System.Collections.ArrayList' to `System.Collections.Generic.IEnumerable<Monodoc.Node>'. An explicit conversion exists (are you missing a cast?)
Mono.Documentation/webdoc.cs(199,87): error CS1662: Cannot convert `lambda expression' to delegate type `System.Func<Monodoc.Node,System.Collections.Generic.IEnumerable<Monodoc.Node>>' because some of the return types in the block are not implicitly convertible to the delegate return type
Mono.Documentation/webdoc.cs(199,40): error CS1928: Type `Monodoc.Node' does not contain a member `TraverseDepthFirst' and the best extension method overload `Mono.Rocks.ObjectRocks.TraverseDepthFirst<Monodoc.Node,Monodoc.Node>(this Monodoc.Node, System.Func<Monodoc.Node,Monodoc.Node>, System.Func<Monodoc.Node,System.Collections.Generic.IEnumerable<Monodoc.Node>>)' has some invalid arguments
Mono.Rocks/ObjectRocks.cs(72,38): (Location of the symbol related to previous error)
Compilation failed: 3 error(s), 1 warnings